# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

RECAPTCHA_PUBLIC_KEY:  '6LcajicTAAAAAP23pEpr8R7kxVnxIFMiSFrP7vxK'
RECAPTCHA_PRIVATE_KEY: '6LcajicTAAAAALK8MsZ8z0XYSXxAuTFNb6c719o9'

production:
 PAGSEGURO_URL_NOTIFICATION: 'http://46.101.84.54/payment/notifications'
 PAGSEGURO_URL_CALLBACK: 'http://46.101.84.54'
 PAGSEGURO_TOKEN: '8EA9624D2D454FFD9FF2B48C2E939380'
 PAGSEGURO_EMAIL: 'vinicius.deoliveira@outlook.com'
 PAGSEGURO_ENVIRONMENT: 'sandbox'
 FACEBOOK_APP_ID: '147187575644754'
 FACEBOOK_APP_SECRET: '9d07c70f343d2726c0264e398f917f28'
 STUDENTCASYSTEM_DATABASE_USER: 'rails'
 STUDENTCASYSTEM_DATABASE_PASSWORD: 'bISSizcEDx'
 STUDENTCASYSTEM_EMAIL_SMTP: 'smtp.gmail.com'
 STUDENTCASYSTEM_EMAIL_PORT: '587'
 STUDENTCASYSTEM_EMAIL_DOMAIN: 'gmail.com'
 STUDENTCASYSTEM_EMAIL_USER: 'viniciusdeoliveirasantos@gmail.com'
 STUDENTCASYSTEM_EMAIL_PASSWORD: '1820goiania'
 STUDENTCASYSTEM_EMAIL_SITE_DOMAIN: 'http://46.101.84.54'
 RECAPTCHA_PUBLIC_KEY:  ''
 RECAPTCHA_PRIVATE_KEY: ''
 AMAZON_S3_BUCKET: ''

development:
 PAGSEGURO_URL_NOTIFICATION: 'http://localhost:3000/payment/notifications'
 PAGSEGURO_URL_CALLBACK: 'http://localhost:3000/estudantes'
 PAGSEGURO_TOKEN: '8EA9624D2D454FFD9FF2B48C2E939380'
 PAGSEGURO_EMAIL: 'vinicius.deoliveira@outlook.com'
 PAGSEGURO_ENVIRONMENT: 'sandbox'
 FACEBOOK_APP_ID: '151222168574628'
 FACEBOOK_APP_SECRET: '8e8fc5dc970a82cb437f49811c039044'
 STUDENTCASYSTEM_DATABASE_USER: 'studentcasystem'
 STUDENTCASYSTEM_DATABASE_PASSWORD: 'studentcasystem'
 STUDENTCASYSTEM_EMAIL_SMTP: 'smtp.gmail.com'
 STUDENTCASYSTEM_EMAIL_PORT: '587'
 STUDENTCASYSTEM_EMAIL_DOMAIN: 'gmail.com'
 STUDENTCASYSTEM_EMAIL_SITE_DOMAIN: 'localhost'
 STUDENTCASYSTEM_EMAIL_USER: 'viniciusdeoliveirasantos@gmail.com'
 STUDENTCASYSTEM_EMAIL_PASSWORD: '1820goiania'
 RECAPTCHA_PUBLIC_KEY:  '6LcajicTAAAAAP23pEpr8R7kxVnxIFMiSFrP7vxK'
 RECAPTCHA_PRIVATE_KEY: '6LcajicTAAAAALK8MsZ8z0XYSXxAuTFNb6c719o9'
 AMAZON_S3_BUCKET: 'studentcasystem'

test:
 PAGSEGURO_URL_NOTIFICATION: 'http://localhost:3000/payment/notifications'
 PAGSEGURO_URL_CALLBACK: 'http://localhost:3000/estudantes'
 PAGSEGURO_TOKEN: '8EA9624D2D454FFD9FF2B48C2E939380'
 PAGSEGURO_EMAIL: 'vinicius.deoliveira@outlook.com'
 PAGSEGURO_ENVIRONMENT: 'sandbox'
 FACEBOOK_APP_ID: '151222168574628'
 FACEBOOK_APP_SECRET: '8e8fc5dc970a82cb437f49811c039044'
 STUDENTCASYSTEM_DATABASE_USER: 'studentcasystem'
 STUDENTCASYSTEM_DATABASE_PASSWORD: 'studentcasystem'
 STUDENTCASYSTEM_EMAIL_SMTP: 'smtp.gmail.com'
 STUDENTCASYSTEM_EMAIL_PORT: '587'
 STUDENTCASYSTEM_EMAIL_DOMAIN: 'gmail.com'
 STUDENTCASYSTEM_EMAIL_SITE_DOMAIN: 'localhost'
 STUDENTCASYSTEM_EMAIL_USER: 'viniciusdeoliveirasantos@gmail.com'
 STUDENTCASYSTEM_EMAIL_PASSWORD: '1820goiania'
 RECAPTCHA_PUBLIC_KEY:  '6LcajicTAAAAAP23pEpr8R7kxVnxIFMiSFrP7vxK'
 RECAPTCHA_PRIVATE_KEY: '6LcajicTAAAAALK8MsZ8z0XYSXxAuTFNb6c719o9'
 AMAZON_S3_BUCKET: 'studentcasystem'