production:
  access_key_id: <%=ENV['AMAZON_S3_ACCESS_KEY_ID']%>
  secret_access_key: <%=ENV['AMAZON_S3_SECRET_ACCESS_KEY_ID']%>

development:
  access_key_id: <%=ENV['AMAZON_S3_ACCESS_KEY_ID']%>
  secret_access_key: <%=ENV['AMAZON_S3_SECRET_ACCESS_KEY_ID']%>

test:
  access_key_id: <%=ENV['AMAZON_S3_ACCESS_KEY_ID']%>
  secret_access_key: <%=ENV['AMAZON_S3_SECRET_ACCESS_KEY_ID']%>